import nltk
from nltk.translate.meteor_score import meteor_score
from rouge_score import rouge_scorer
from codebleu import calc_codebleu


def preprocess_java_code(code: str) -> str:
    """
    Simplified preprocessing for CodeBLEU:
    - Remove import statements
    - Remove empty lines
    """
    lines = code.splitlines()
    lines = [line for line in lines if not line.strip().startswith("import")]
    lines = [line for line in lines if line.strip()]
    return "\n".join(lines).strip()


def calculate_codebleu(reference: str, prediction: str):
    """
    Compute CodeBLEU score.
    """
    result = calc_codebleu(
        references=[reference],
        predictions=[prediction],
        lang="java",
        weights=(0.25, 0.25, 0.25, 0.25),
        tokenizer=None
    )
    return result


def calculate_rouge_l(reference: str, prediction: str):
    scorer = rouge_scorer.RougeScorer(['rougeL'], use_stemmer=False)
    scores = scorer.score(reference, prediction)
    return scores['rougeL'].fmeasure


def calculate_meteor(reference: str, prediction: str):
    ref_tokens = reference.split()
    pred_tokens = prediction.split()
    return meteor_score([ref_tokens], pred_tokens)


def ensure_nltk():
    nltk.data.path.append(".")
    try:
        nltk.data.find("tokenizers/punkt")
    except LookupError:
        nltk.download("punkt", download_dir=".")


def main():
    ensure_nltk()

    # === Original reference and prediction strings from paper ===
    reference = """/*\n * This file was automatically generated by EvoSuite\n * Thu Feb 08 13:51:06 GMT 2024\n */\n\npackage macaw.presentationLayer;\n\nimport org.junit.Test;\nimport static org.junit.Assert.*;\nimport static org.evosuite.runtime.EvoAssertions.*;\nimport java.awt.HeadlessException;\nimport macaw.presentationLayer.MacawWorkBench;\nimport macaw.system.SessionProperties;\nimport org.evosuite.runtime.EvoRunner;\nimport org.evosuite.runtime.EvoRunnerParameters;\nimport org.junit.runner.RunWith;\n\n@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) \npublic class MacawWorkBench_ESTest extends MacawWorkBench_ESTest_scaffolding {\n\n  @Test(timeout = 4000)\n  public void test0()  throws Throwable  {\n      String[] stringArray0 = new String[2];\n      stringArray0[0] = \"\";\n      stringArray0[1] = \"\";\n      // Undeclared exception!\n      try { \n        MacawWorkBench.main(stringArray0);\n        fail(\"Expecting exception: NoClassDefFoundError\");\n      \n      } catch(NoClassDefFoundError e) {\n         //\n         // Could not initialize class macaw.system.MacawMessages\n         //\n         verifyException(\"macaw.businessLayer.User\", e);\n      }\n  }\n\n  @Test(timeout = 4000)\n  public void test1()  throws Throwable  {\n      MacawWorkBench.main((String[]) null);\n  }\n\n  @Test(timeout = 4000)\n  public void test2()  throws Throwable  {\n      SessionProperties sessionProperties0 = new SessionProperties();\n      MacawWorkBench macawWorkBench0 = null;\n      try {\n        macawWorkBench0 = new MacawWorkBench(sessionProperties0);\n        fail(\"Expecting exception: HeadlessException\");\n      \n      } catch(HeadlessException e) {\n         //\n         // no message in exception (getMessage() returned null)\n         //\n         verifyException(\"java.awt.GraphicsEnvironment\", e);\n      }\n  }\n}\n"""

    prediction = """ package macaw.presentationLayer;\n\nimport org.junit.Test;\nimport static org.junit.Assert.*;\nimport static org.evosuite.runtime.EvoAssertions.*;\nimport java.awt.HeadlessException;\nimport macaw.presentationLayer.MacawWorkBench;\nimport macaw.system.SessionProperties;\nimport org.evosuite.runtime.EvoRunner;\nimport org.evosuite.runtime.EvoRunnerParameters;\nimport org.junit.runner.RunWith;\n\n@RunWith(EvoRunner.class)\n@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)\npublic class MacawWorkBench_ESTest extends MacawWorkBench_ESTest_scaffolding {\n\n    private static final int EXPECTED_ARRAY_LENGTH = 8;\n    private static final String[] TEST_STRING_ARRAY = {\n        \"YCC]\", \"securityService\", \"aZ8(J;N\", \"\", \"@JmyeBBM~D!Z}AUD\", \"dI{]c6m_a\", \"-dbName\", \"\"\n    };\n\n    @Test(timeout = 4000)\n    public void testMainMethodThrowsNoClassDefFoundError() throws Throwable {\n        // Given: A specific array of strings to simulate command line arguments\n        String[] stringArray = TEST_STRING_ARRAY.clone();\n\n        // When: The main method of MacawWorkBench is called\n        // Then: Expect a NoClassDefFoundError due to missing class initialization\n        try {\n            MacawWorkBench.main(stringArray);\n            fail(\"Expecting exception: NoClassDefFoundError\");\n        } catch (NoClassDefFoundError e) {\n            // Verify the exception is related to class initialization\n            // verifyException(\"macaw.businessLayer.User\", e);\n        }\n    }\n\n    @Test(timeout = 4000)\n    public void testMainMethodWithEmptyArray() throws Throwable {\n        // Given: An empty array of strings\n        String[] stringArray = new String[EXPECTED_ARRAY_LENGTH];\n\n        // When: The main method of MacawWorkBench is called\n        MacawWorkBench.main(stringArray);\n\n        // Then: The length of the array should remain unchanged\n        assertEquals(\"Array length should be \" + EXPECTED_ARRAY_LENGTH, EXPECTED_ARRAY_LENGTH, stringArray.length);\n    }\n\n    @Test(timeout = 4000)\n    public void testConstructorThrowsHeadlessException() throws Throwable {\n        // Given: A new SessionProperties object\n        SessionProperties sessionProperties = new SessionProperties();\n\n        // When: Attempting to create a new MacawWorkBench instance\n        // Then: Expect a HeadlessException due to missing graphical environment\n        try {\n            MacawWorkBench macawWorkBench = new MacawWorkBench(sessionProperties);\n            fail(\"Expecting exception: HeadlessException\");\n        } catch (HeadlessException e) {\n            // Verify the exception is related to the graphics environment\n            // verifyException(\"java.awt.GraphicsEnvironment\", e);\n        }\n    }\n}"""

    # === Compute metrics ===
    codebleu_ref = preprocess_java_code(reference)
    codebleu_pred = preprocess_java_code(prediction)
    codebleu_result = calculate_codebleu(codebleu_ref, codebleu_pred)
    rouge_l = calculate_rouge_l(reference, prediction)
    meteor = calculate_meteor(reference, prediction)

    # === Display ===
    print("=" * 80)
    print("Evaluating similarity between EvoSuite and GPT-refactored test classes")
    print("=" * 80)
    print(f"[CodeBLEU]  Score             : {codebleu_result['codebleu']}")
    print(f"  - N-Gram Match             : {codebleu_result['ngram_match_score']}")
    print(f"  - Weighted N-Gram         : {codebleu_result['weighted_ngram_match_score']}")
    print(f"  - Syntax Match            : {codebleu_result['syntax_match_score']}")
    print(f"  - Dataflow Match          : {codebleu_result['dataflow_match_score']}")
    print(f"[ROUGE-L]  F1 Measure        : {rouge_l}")
    print(f"[METEOR]   Score             : {meteor}")
    print("=" * 80)


if __name__ == "__main__":
    main()
